### PR TITLE
Update fork to 2.6

### PR DESCRIPTION
**Pull request by mloberg**

### CODE REVIEW

**Comment by natebrunette** [comment]
@sumpygump @konrness This look good to you?

**Comment by ReservedDeveloper** [comment]
I think one point we could debate is the validity of updating our fork to a non-LTS version. Is the intent for us to keep on the latest stable, or latest LTS?

**Comment by mattjanssen** [comment]
I prefer the latest. I have yet to run security updates for a client on an old project, and I haven't seen clients run updates themselves, either.

Remember that even non-LTS versions get 14 months of security fixes.

**Comment by mloberg** [comment]
Could this PR be created as a "2.6" branch and keep the existing 2.3 branch around? That way if you needed to you could still create projects from the 2.3 release. `composer create-project nerdery/symfony-standard path "2.3.*"`

**Comment by tonynelson19** [comment]
I feel like we're going to start chasing our tails on this one. What if we kill the fork and use the [Symfony Installer](https://github.com/symfony/symfony-installer) instead?

**Comment by mloberg** [comment]
What was the reason for the fork? I use the phing stuff, but that could be easily added to projects that want it. Maybe going with the installer would be better because then we would be waiting around months for our fork to be updated.

**Comment by tonynelson19** [comment]
The fork has a customized composer.json to include more common bundles and dev tools, a Phing script to handle creating builds and releases, and a new front controller (web/index.php) that uses an environment variable to load the application in prod or dev mode.

I customize the composer.json and build.xml files so much on each project that the fork doesn't add much value to my projects, aside from the convenience of a cleaner URL due to web/index.php.

**Comment by mattjanssen** [comment]
Step 1: "Installing the installer"

I'll admit I've never used the Nerdery fork either. I'll grab pieces from the build.xml, index.php, .gitignore and composer.json files, but that's all. I usually just clone the Symfony Standard repo.

**Comment by ReservedDeveloper** [comment]
This (namely, the index.php file) feels like something that could be accomplished via phing. Whenever you do an install, instead of updating an environment variable, simply rename a file. Granted, this doesn't address the composer or other file changes, but I think it does get closer to a self-contained fork alternative.

**Comment by tonynelson19** [comment]
Not saying this is a great idea, but we could (in theory) create our own NerderyBundle that has a composer hook to adjust the standard as necessary, pull in any dev dependencies such as phing, and install a default build script. I fear this would lead to further issues with trying to maintain version compatibility though.

Maybe we just need really good documentation on what developers should add, adjust, install, etc... and why.

**Pull request closed without merging**
